guziki i slidery
trzeciak20p/balls pull request #13
Opened 2024-09-16 17:07 UTC by trzeciak20p

2024-09-16 18:57 UTC, abfipes12 reviewed
komentaz z vscode

2024-09-16 20:37 UTC, merged

2024-09-16 21:11 UTC, pncp requested changes

2024-09-16 21:11 UTC, pncp commented on src/classes/button.h
> +inline std::vector<Button> buttons; // Vector for storing every class instance
Nie lepiej jako właściwość statyczna?

2024-09-16 21:11 UTC, pncp commented on src/classes/button.cpp
> +    this->onHoverRelease(); // sets default colors for text and body
Ja bym zrobił funkcje na ustawienie kolorów i ją wywołał w onHoverRelease - poprawia czytelność kodu i nie trzeba dawać komentarza - plus łatwiej potem dać poprawki

2024-09-16 21:11 UTC, pncp commented on src/classes/button.cpp
> +    std::fprintf(stderr, "clicked  :D \r\n");
Obstawiam że debug?

2024-09-16 21:11 UTC, pncp commented on src/classes/button.h
> +    bool checkHover(sf::Vector2i pos);
Kolejność się nie zgadza z plikiem cpp >:)

2024-09-16 21:11 UTC, pncp commented on src/classes/fontLoader.cpp
> +// klasa z tego miałaby sens
Jeśli miałaby sens to albo trzeba to zrobić albo wywalić komentarz

2024-09-16 21:11 UTC, pncp commented on src/classes/fontLoader.cpp
> +} // namespace bnw
?

2024-09-16 21:11 UTC, pncp commented on src/classes/fontLoader.cpp
> +}
Brakuje tutaj wcięcia na początku, ale wygląda jak decyzja stylistyczna

2024-09-16 21:11 UTC, pncp commented on src/classes/game.cpp
> +
Została pusta linia, wcześniej pustej linii nie było przed break

2024-09-16 21:11 UTC, pncp commented on src/classes/game.cpp
> -        m_mouse = sf::Mouse::getPosition(*m_window);
Jesteśmy pewni że mouse jest updated? Czy po prostu wierzymy że przed mousepress mouse będzie już zupdatowane

2024-09-16 21:11 UTC, pncp commented on src/classes/game.h
> +    Board       *to_board{};
Jak już alignujemy to można alignąć z tym niżej

2024-09-16 21:11 UTC, pncp commented on src/classes/slider.h
> +    // void update(float value);
?

2024-09-16 21:11 UTC, pncp commented on src/classes/slider.h
> +    sf::RectangleShape m_controler{};
Controller?

2024-09-16 21:11 UTC, pncp commented on src/classes/slider.cpp
> +        m_controler.setPosition(m_pos.x, m_body.getPosition().y);
Slidery blokują myszkę? Nie lepiej dać myszce się ruszać a slider działa relatywnie? (Aka żeby działały slidery jak na łyndołsie)

2024-09-16 21:11 UTC, pncp commented on src/main.cpp
> +    buttons.push_back(Button(400, 400, 200, 100, "bbbb"));
Prosta zasada - jeśli czegoś nie da się sensownie nazwać to znaczy że nie jest to potrzebne

2024-09-16 21:11 UTC, pncp commented on src/main.cpp
> +}
Nie mam pojęcia co tu się stało

2024-09-16 21:16 UTC, abfipes12 commented on src/classes/button.h
> +inline std::vector<Button> buttons; // Vector for storing every class instance
(chcesz mieć vector<button> w clasie button, coprawda gcc jest nagięcie mądry i to zkompiluje, ale clang jusz sie zesra)

2024-09-16 21:19 UTC, abfipes12 commented on src/classes/slider.h
> +    // void update(float value);
bedzię inherance update prawdopodobnie na tym by nie było body

2024-09-16 21:19 UTC, abfipes12 commented on src/classes/slider.h
> +    sf::RectangleShape m_controler{};
ten mniejszy dongiel w sliderze

2024-09-16 21:21 UTC, pncp commented on src/classes/slider.h
> +    sf::RectangleShape m_controler{};
Chodzi mi o pisownię

2024-09-16 21:23 UTC, pncp commented on src/classes/slider.h
> +    // void update(float value);
Ok, chodzi mi o to czemu to jest zakomentowane - albo należy zostawić puste albo wywalić dopóki nie będzie potrzebne - ewentualnie zastąpić komentarzem typu TODO: ZROBIC METODE UPDATE

2024-09-16 21:24 UTC, abfipes12 commented on src/main.cpp
> +}
jak sprawdzałem co daje '\n' na koncu pliku to ze w hederah w starych wersjach cpp na starych kompilatorach, a bynajmniej na ułomnych jak microsoftu sie psuło (2011), + znikało "No newline at end of file" na githabah

(nie jest jusz 2011 wiec mozna break newline na końcu update), (clang format doda mozliwość automatycznego usuwania '\n' na koncu w wersji 19, a narazie jest 18.coś

2024-09-16 21:25 UTC, abfipes12 commented on src/classes/slider.h
> +    sf::RectangleShape m_controler{};
pro

2024-09-16 21:26 UTC, pncp commented on src/main.cpp
> +}
Czyli testowałeś losowe rzeczy na plikach z kodem. Ok. Wywal to proszę bo wygląda okropnie.

2024-09-16 21:26 UTC, pncp commented on src/classes/slider.h
> +    sf::RectangleShape m_controler{};
Myślę że decyzje o tym czy ta pisownia jest pro czy nie należy zostawić Markowi

2024-09-16 21:28 UTC, abfipes12 commented on src/classes/button.cpp
> +    std::fprintf(stderr, "clicked  :D \r\n");
to bedzie raczej działać inaczej gdyz zakladam ze ruzne przyciski bedą robiły ruzne rzeczy
\

2024-09-16 21:31 UTC, pncp commented on src/classes/button.cpp
> +    std::fprintf(stderr, "clicked  :D \r\n");
Więc sama wiadomość jest do wywalenia

2024-09-16 21:31 UTC, abfipes12 commented on src/classes/button.h
> +    bool checkHover(sf::Vector2i pos);
musze o tym poczytać bo chyba coś o tym słyszałem ale nie widziałem opcji w linterze by to przemieszczała

2024-09-16 21:35 UTC, pncp commented on src/classes/button.h
> +    bool checkHover(sf::Vector2i pos);
Albo możesz po prostu zamienić kolejność

2024-09-16 21:43 UTC, abfipes12 commented on src/classes/slider.cpp
> +        m_controler.setPosition(m_pos.x, m_body.getPosition().y);
nie widze gdzie to blokuje, objaśnij

2024-09-16 23:18 UTC, abfipes12 commented on src/classes/button.h
> +    bool checkHover(sf::Vector2i pos);
ogólnie w innych klasach jest sortowanie wzglendem dłógości deklaracji, gdyz nie znalazłem zalecen

2024-09-16 23:26 UTC, abfipes12 commented on src/main.cpp
> +    buttons.push_back(Button(400, 400, 200, 100, "bbbb"));
bardzo javowe podejscie było przy konstruowaniu (emplace_back lepsze od push_back)
to nie jest tak ze nie da sie przycisków nazwać sensownie tylko bardziej one nie robią nic sensownego jeszcze,

2024-09-17 13:58 UTC, trzeciak20p commented on src/classes/fontLoader.cpp
> +} // namespace bnw
??

2024-09-17 13:59 UTC, trzeciak20p commented on src/classes/fontLoader.cpp
> +}
nie brakuje bo nazwy są na tej samej odległości

2024-09-17 14:01 UTC, trzeciak20p commented on src/classes/game.cpp
> -        m_mouse = sf::Mouse::getPosition(*m_window);
mysz powinna być (bo aktualnie nie jest) co tick (klatke na razie też)
 więc wierzymy

2024-09-17 14:01 UTC, trzeciak20p commented on src/classes/game.h
> +    Board       *to_board{};
?