Smirk update
trzeciak20p/balls pull request #15
Opened 2024-09-23 17:12 UTC by trzeciak20p

Dużo rzeczy wsm:
- map loader
- gui scenariusze
- struktura folderów
(może nie widać ale dużo)

2024-09-23 17:47 UTC, pncp requested changes
13/49 files viewed

2024-09-23 17:47 UTC, pncp commented on README.md
> +## How to play:
nie zaśmiecajmy historii pliku

2024-09-23 17:47 UTC, pncp commented on assets/maps/map1
> +b 700 600 20 rgb  0 0 0
na ile intencja jest aby formatować pliki z mapami? po rgb jest dużo spacji co implikuje formatowanie ładne ale w reszcie pliku tego nie ma.

2024-09-23 17:47 UTC, pncp commented on cmake/compilerWarnings.cmake
> +
dajmy tutaj komentarz coś w stylu w stylu TODO żeby jak komuś sie nudzi i nie ma co robić to wyszukuje w projekcie frazę TODO i robi to co mu się aktualnie chce

2024-09-23 17:47 UTC, pncp commented on src/classes/chungus.h
komentarz że to ładuje absolutnie wszystko żeby nie trzeba było ładować osobno?

2024-09-23 17:47 UTC, pncp commented on src/classes/chungus.h
> +#include <vector>
czy naprawdę to wszystko musimy zawsze załączać? rozumiem jeśli jest to używane w połowie plików, ale jeśli jest w 3 plikach użyte to może lepiej tylko tam to załączyć?

2024-09-23 17:47 UTC, pncp commented on src/classes/board/ball.h
> +#include "ball.h"
czy to napewno powinno tutaj być?

2024-09-23 17:47 UTC, pncp commented on src/classes/board/ball.cpp
wcześniej był komentarz o destruktorze do zrobienia - jaki jest tego status?

2024-09-23 17:54 UTC, pncp commented on src/classes/board/ball.cpp
> +void Ball::cornerCheck(const Wall& wall, Vec2f new_pos)
nie rozumiem co ta funkcja ma robić - cornerCheck implikuje że funkcja powinna zwracać true/false

2024-09-23 17:54 UTC, pncp commented on src/classes/utils_2d.h
> +float getDistacne(Vec2f a, Vec2f b);
typo

2024-09-23 17:56 UTC, abfipes12 commented on src/classes/utils_2d.h
> +float getDistacne(Vec2f a, Vec2f b);
ale pro, + float getDistacne(Vec2f a); powinno być getLength(), i po trzecie czemu to ma get na początku wszystko ja to nawet nie są getery

2024-09-23 17:59 UTC, abfipes12 commented on src/classes/board/ball.h
> +#include "ball.h"
wątpliwe

2024-09-23 17:59 UTC, pncp commented on src/classes/board/wall.h
> +    Wall(Vec2f left_top, Vec2f width_height, Type type = normal);
czyim pomysłem to było.

2024-09-23 17:59 UTC, abfipes12 commented on src/classes/board/ball.cpp
status buta, wsomie nie wiem, nie pamietam bym go usuwał

2024-09-23 18:01 UTC, abfipes12 commented on src/classes/board/ball.cpp
> +void Ball::cornerCheck(const Wall& wall, Vec2f new_pos)
wcześniej funkcja robiła absolutnie nic, teraz wsomie updatuje miejsce piłki w przypadku gdyby piłka miała udeżyć w korner
, jak inne check funckje w Ball::

2024-09-23 18:03 UTC, pncp commented on src/classes/utils_2d.h
> +float getDistacne(Vec2f a, Vec2f b);
też prawda - wnioskuję o zmianę nazwy na checkDistance

2024-09-23 18:04 UTC, trzeciak20p commented on src/classes/chungus.h
tak

2024-09-23 18:06 UTC, pncp commented on src/classes/board/ball.cpp
> +void Ball::cornerCheck(const Wall& wall, Vec2f new_pos)
i w ogóle konwencja nazywania mi się tutaj nie podoba - najpierw jest cornerCheck a potem jest checkBounce

2024-09-23 18:06 UTC, trzeciak20p commented on README.md
> +## How to play:
czyli mamy zostawiać spacje z dupy?

2024-09-23 18:07 UTC, trzeciak20p commented on src/classes/board/ball.cpp
to było do wcześniejszych założeń
teraz destruktor jest useless

2024-09-23 18:13 UTC, abfipes12 commented on src/classes/chungus.h
> +#include <vector>
clean code strategie grzegorza, zapewne przesto grzegorz ma długie kompilacje

2024-09-23 18:18 UTC, abfipes12 commented on README.md
> +## How to play:
a to właśnie jej nie usuwa?

2024-09-23 18:21 UTC, abfipes12 commented on assets/maps/map1
> +b 700 600 20 rgb  0 0 0
chyba nie formatujemy będziemu map

2024-09-23 18:28 UTC, abfipes12 commented on cmake/compilerWarnings.cmake
> +
Todo: dodam todo do tego pliku

2024-09-23 18:31 UTC, abfipes12 commented on src/classes/board/wall.h
> +    Wall(Vec2f left_top, Vec2f width_height, Type type = normal);
nieironicznie https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i4-make-interfaces-precisely-and-strongly-typed

2024-09-23 18:32 UTC, abfipes12 commented on src/classes/chungus.h
niestety nie ładuje wszystkiego tylko większość

2024-09-23 18:48 UTC, pncp commented on src/classes/board/ball.cpp
> +void Ball::cornerCheck(const Wall& wall, Vec2f new_pos)
zmodyfikować nazwę na changeVelocityBasedOnNearestCorner

2024-09-23 18:49 UTC, pncp commented on src/classes/board/ball.cpp
> +void Ball::sideCheck(const Wall& wall, Vec2f new_pos)
changeVelocityBasedOnWall

2024-09-23 18:49 UTC, pncp commented on src/classes/board/ball.cpp
> +
TODO: naprawić fizykę odbijania od corneru (i generalnie naprawić)

2024-09-23 18:57 UTC, trzeciak20p commented on src/classes/board/ball.cpp
> +void Ball::sideCheck(const Wall& wall, Vec2f new_pos)
"basedOnWall" nie ma sensu bo podajesz wall w argumencie

2024-09-23 18:58 UTC, pncp commented on README.md
> +## How to play:
no ok

2024-09-23 18:58 UTC, pncp commented on cmake/compilerWarnings.cmake
> +
TODO: zrób commita gdzie to robisz

2024-09-23 18:58 UTC, pncp commented on src/classes/chungus.h
mój punkt ciągle stoi.

2024-09-23 19:01 UTC, pncp commented on src/classes/board/wall.h
> +    Wall(Vec2f left_top, Vec2f width_height, Type type = normal);
dziękuję za informację.

2024-09-23 19:03 UTC, trzeciak20p commented on src/classes/chungus.h
tego nie widać jak popatrzysz na plik?

2024-09-23 19:03 UTC, trzeciak20p commented on src/classes/chungus.h
wsn zmiana nazwy tak ale po co komentarz

2024-09-23 19:04 UTC, trzeciak20p commented on src/classes/chungus.h
> +#include <vector>
grześ mówił że wrencz przeciwnie, jest szybsza kompilacja
![image](https://github.com/user-attachments/assets/17d3d65d-9b0e-4f63-a5e0-2b709b1aaae2)

2024-09-23 19:28 UTC, pncp commented on src/classes/board/board.cpp
> +    if (Ball::active_ball == nullptr)
wiem że chojec zmiana ale można dać tu `if (!Ball::active_ball)`

2024-09-23 19:31 UTC, pncp commented on src/classes/board/board.cpp
> +    Ball::active_ball->setFillColor(Ball::active_ball->m_color);
a kolor sie wgl zmienia jak sie kliknie? bo nie znalazłem nigdzie

2024-09-23 19:42 UTC, pncp commented on src/classes/board/chargeMeter.cpp
> +void ChargeMeter::update(Vec2f last_click, Vec2f mouse)
last click ewentualnie można zmienić na anchor point

2024-09-23 19:45 UTC, pncp commented on src/classes/utils_2d.h
> +float getAngle(Vec2f a);
checkAngle?

2024-09-23 19:45 UTC, pncp commented on src/classes/utils_2d.h
> -{ // Balls n' Walls
ja bym jednak przywrócił

2024-09-24 13:06 UTC, pncp commented on src/classes/gui/button.cpp
> +           pos.y <= getPosition().y + getSize().y;
nie ma to jak formatowanie według swojej lokalnej szerokości ekranu - either do rozdzielenia na x i y or na 4 linijki

2024-09-24 13:08 UTC, pncp commented on src/classes/gui/button.cpp
Przychodzi mi do głowy że potencjalnie można chcieć guzikiki o różnych kolorach - na ile jest to sprawa którą należy się zająć teraz, nie do mnie należy ta decyzja.

2024-09-24 13:26 UTC, pncp commented on src/classes/gui/slider.cpp
> +void Slider::onUse(float height)
zazwyczaj funkcje typu onUse, onClick nie przyjmują parametrów bo nasłuchują - zmieniłbym nazwę na changePos, move, slide etc.

2024-09-24 13:37 UTC, pncp commented on src/classes/board/ball.cpp
> +void Ball::sideCheck(const Wall& wall, Vec2f new_pos)
faktycznie, zbyt skomplikowałem, bez sensu

2024-09-24 13:39 UTC, pncp commented on src/classes/gui/slider.cpp
> +           pos.y <= getPosition().y + getSize().y;
inconsistant formatowanie

2024-09-24 13:41 UTC, pncp commented on src/classes/gui/slider.cpp
> +        m_controler.setPosition(getPosition());
jest ku temu funkcjonalny powód?

2024-09-24 14:01 UTC, trzeciak20p commented on src/classes/utils_2d.h
> -{ // Balls n' Walls
nie było w innych miejscach
każdy raczej wie jakie ma rozwinięcie
to nie tak że nazwa ma znaczenie dla zawartości, bo zawiera ogólno projektowe rzeczy

2024-09-24 14:06 UTC, trzeciak20p commented on src/classes/gui/button.cpp
tldr - łatwe do rozwinięcia
Myślałem nad ewentualnym podzieleniem guzików na grupy/podklasy, które miałby inne sety kolorów ale dalej ustalanych z góry. Ewentualnie można wrzucić to do konstruktora ale to będzie proste.
Jeśli chodzi o wybór map, tam można zrobić nawet img na tło, ale to można walnąć podklase buttona czy coś takiego.

2024-09-24 14:08 UTC, pncp commented on src/classes/event.h
> +};
powtórzenie z GUI - najlepiej by było wywalić do osobnego pliku Event.h

2024-09-24 14:08 UTC, trzeciak20p commented on src/classes/gui/slider.cpp
> +           pos.y <= getPosition().y + getSize().y;
Trzeba by było zmienić formatter a nwm jak

2024-09-24 14:11 UTC, trzeciak20p commented on src/classes/gui/slider.cpp
> +        m_controler.setPosition(getPosition());
Tak,
Slider dziedziczy z sf::RectangleShape i w nim przechowujemy pozycje żeby nie zaśmiecać pamięci nowymi zmiennymi

2024-09-24 14:13 UTC, trzeciak20p commented on src/classes/event.h
> +};
fun fact: tych plików (event.h/.cpp) miało nie być

2024-09-24 14:16 UTC, trzeciak20p commented on src/classes/gui/slider.cpp
> +void Slider::onUse(float height)
zmienione

2024-09-24 14:20 UTC, trzeciak20p commented on src/classes/board/board.cpp
> +    Ball::active_ball->setFillColor(Ball::active_ball->m_color);
tak
jest w chargeMeter XD

2024-09-24 14:34 UTC, trzeciak20p commented on src/classes/board/board.cpp
> +    if (Ball::active_ball == nullptr)
linter mówi że tak jest bardziej czytelnie

2024-09-24 15:05 UTC, trzeciak20p commented on src/classes/board/chargeMeter.cpp
> +void ChargeMeter::update(Vec2f last_click, Vec2f mouse)
done

2024-09-24 15:05 UTC, trzeciak20p commented on src/classes/gui/button.cpp
> +           pos.y <= getPosition().y + getSize().y;
formatter moment

2024-09-25 08:25 UTC, trzeciak20p commented on src/classes/gui/button.cpp
> +           pos.y <= getPosition().y + getSize().y;
clang chyba nie pozwala tego ładnie sformatować

2024-09-25 08:26 UTC, trzeciak20p commented on src/classes/board/ball.cpp
> +
imo bez sensu pisać todo jeśli ogólnie wiemy że trzeba plus to nie tak, że coś konkretnego można by wrzucić do komentarza

2024-09-25 08:27 UTC, trzeciak20p commented on src/classes/gui/slider.cpp
> +           pos.y <= getPosition().y + getSize().y;
to co wyżej, nie ma dobrego rozwiązania chyba

2024-09-25 12:17 UTC, pncp approved these changes

2024-09-25 12:18 UTC, merged